#include "ModemManager.h"
/*
// Global variables referenced by esp_modem.c
int CONFIG_EXAMPLE_UART_RX_BUFFER_SIZE;
int CONFIG_EXAMPLE_UART_TX_BUFFER_SIZE;
int CONFIG_EXAMPLE_UART_EVENT_QUEUE_SIZE;
int CONFIG_EXAMPLE_UART_PATTERN_QUEUE_SIZE;
uint32_t CONFIG_EXAMPLE_UART_EVENT_TASK_STACK_SIZE;
UBaseType_t CONFIG_EXAMPLE_UART_EVENT_TASK_PRIORITY;

int CONFIG_EXAMPLE_UART_MODEM_TX_PIN;
int CONFIG_EXAMPLE_UART_MODEM_RX_PIN;
int CONFIG_EXAMPLE_UART_MODEM_RTS_PIN;
int CONFIG_EXAMPLE_UART_MODEM_CTS_PIN;

const char *CONFIG_EXAMPLE_MODEM_APN;

const char *CONFIG_EXAMPLE_MODEM_PPP_AUTH_USERNAME;
const char *CONFIG_EXAMPLE_MODEM_PPP_AUTH_PASSWORD;
*/

namespace cima::system::network {

}