SET "ESP_TOOLCHAIN_DIR=e:/SW/ESP"
SET "ESP_PROJECT=%cd%"

cd /D %ESP_TOOLCHAIN_DIR%/esp-idf
call export.bat

cd /D %ESP_PROJECT%

SET "CXX=xtensa-esp32-elf-g++"
SET "IOT_SOLUTION_PATH=%ESP_TOOLCHAIN_DIR%/esp-iot-solution"
SET "AZURE_SDK_C_PATH=%ESP_TOOLCHAIN_DIR%/esp-azure"
SET "BOOST_ROOT=%ESP_TOOLCHAIN_DIR%/boost_1_71_0"
SET "IDF_PATH=%ESP_TOOLCHAIN_DIR%/esp-idf"